import {
  type SimpleIcon,
  siAxios,
  siChartdotjs,
  siClaude,
  siCloudinary,
  siGooglebigquery,
  siJsonwebtokens,
  siLivekit,
  siPassport,
  siPostman,
  siSemanticweb,
  siStyledcomponents,
  siSwagger,
  siCss,
  siCursor,
  siD3,
  siDocker,
  siExpo,
  siExpress,
  siFirebase,
  siFramer,
  siGit,
  siGithubactions,
  siGooglecloud,
  siHtml5,
  siJavascript,
  siJest,
  siLeaflet,
  siMui,
  siNextdotjs,
  siNodedotjs,
  siPnpm,
  siPython,
  siRadixui,
  siReact,
  siReactquery,
  siRedux,
  siSanity,
  siShadcnui,
  siSocketdotio,
  siStorybook,
  siStripe,
  siSupabase,
  siTailwindcss,
  siTestinglibrary,
  siTypescript,
  siVercel,
  siVite,
  siVitest,
  siVuedotjs,
  siVuetify,
  siZod,
} from "simple-icons";

const icons: Record<string, SimpleIcon> = {
  TypeScript: siTypescript,
  JavaScript: siJavascript,
  Python: siPython,
  HTML: siHtml5,
  CSS: siCss,
  "Testing Library": siTestinglibrary,
  "GitHub Actions": siGithubactions,
  React: siReact,
  "Next.js": siNextdotjs,
  "Vue 3": siVuedotjs,
  Vite: siVite,
  Tailwind: siTailwindcss,
  MUI: siMui,
  Radix: siRadixui,
  shadcn: siShadcnui,
  Vuetify: siVuetify,
  "Motion": siFramer,
  "Node.js": siNodedotjs,
  Express: siExpress,
  Supabase: siSupabase,
  Firebase: siFirebase,
  "Google Cloud": siGooglecloud,
  BigQuery: siGooglebigquery,
  JWT: siJsonwebtokens,
  Passport: siPassport,
  Cloudinary: siCloudinary,
  Swagger: siSwagger,
  Postman: siPostman,
  "RDF & Turtle": siSemanticweb,
  LiveKit: siLivekit,
  Axios: siAxios,
  "styled-components": siStyledcomponents,
  Docker: siDocker,
  Vercel: siVercel,
  Stripe: siStripe,
  Sanity: siSanity,
  "Socket.IO": siSocketdotio,
  "TanStack Query": siReactquery,
  "Redux Toolkit": siRedux,
  D3: siD3,
  Leaflet: siLeaflet,
  "Chart.js": siChartdotjs,
  Zod: siZod,
  Vitest: siVitest,
  Jest: siJest,
  Storybook: siStorybook,
  Expo: siExpo,
  pnpm: siPnpm,
  Git: siGit,
  Cursor: siCursor,
  Claude: siClaude,
};

export function techIcon(name: string): SimpleIcon | undefined {
  return icons[name];
}
